#!/bin/bash

if [ -z "${BOOKLETMACRO_DIR}" ]; then
    BOOKLETMACRO_DIR="$HOME/.bookletMacro"
fi

bookletmacro_zip_file="${BOOKLETMACRO_DIR}/installArchive.zip"

echo "creating directory in home folder..."
mkdir -p "${BOOKLETMACRO_DIR}"

echo "downloading jPDF and .workflow in a ZIP archive..."
curl -LOk "https://github.com/jsphweid/bookletMacro/raw/master/mac-osx/installArchive.zip" -o "${bookletmacro_zip_file}"

echo "unzipping archive..."
unzip -qo "${bookletmacro_zip_file}" -d "${BOOKLETMACRO_DIR}"

echo "prompting to install service..."
open "${BOOKLETMACRO_DIR}/Booklet Macro v0.3.1.workflow"